before_script:
  - source /etc/profile
  - GIT_SSL_NO_VERIFY=true git submodule update --init --recursive

stages:
  - doc
  - test

doc:
  stage: doc
  script:
    - pyenv local 3.5.1
    - make install
    - make doc
    - rsync -av --delete doc/_build/html/ doc-sync@docs.adfinis-sygroup.ch:/var/www/html/public/freeze/

test27:
  stage: test
  script:
    - pyenv local 2.7.11
    - make test

test3:
  stage: test
  script:
    - pyenv local 3.5.1
    - make test
