language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - USE_CYTHON=false
  - USE_CYTHON=true
# command to install dependencies
install:
 - "pip install -r requirements.txt --use-mirrors"
 - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"
# command to run tests
script: ./.travis-test.sh
